### ISSUE TITLE
Implement nested commands

### ISSUE THREAD

**Issue by calhauz** [dreadster3/buddy#6]
I would consider that instead of having a simple object with scripts we could have a more complex nested object where the combined keys are the nested commands and the final leaf is the actual cmd to be called. So that using buddy any person could build a cli like tool:

```jsonc
{
  "name": "my-daily-tasks-helper",
  "version": "0.0.1",
  "description": "A new buddy project",
  "author": "Anonymous",
  "scripts": {
    "app": {
      "build" : "...",
      "start" : "...",
      "test" : {
        "service_1": "...",
        "service_2": "..."
      },
      "deploy" : "..."
    },
    "infra": {
      "plan": "...",
      "destroy": "...",
      "apply": "..."
    }
   }
}
```

Possible cmds would be:
```bash
buddy run app build
buddy run app start
buddy run app test service_1
buddy run app test service_2
buddy run app deploy
buddy run infra plan
buddy run infra destroy
buddy run infra apply
```

Maybe a good way to turn your helpfull scripts or even call simple comands in a CLI like tool where we simply configure the json.

**Comment by dreadster3** [comment]
I believe that adding something like that would add too much complexity to the usage of buddy, and this is supposed to be as simplified as possible. Also this is already possible to achieve in a clean way using a separator, so something like
```json
{
  "scripts": {
    "app": {
      "build": "...",
      "start": "...",
      "test": {
        "service_1": "...",
        "service_2": "..."
      },
      "deploy": "..."
    },
    "infra": {
      "plan": "...",
      "destroy": "...",
      "apply": "..."
    }
  }
}
```
Can easily be translated to something like this
```json
{
  "scripts": {
    "app:build": "...",
    "app:start": "...",
    "app:test:service_1": "...",
    "app:test:service_2": "...",
    "app:deploy": "...",
    "infra:plan": "...",
    "infra:destroy": "...",
    "infra:apply": "..."
  }
}
```
Which i believe comes to a much cleaner configuration file and the only difference in usage is that instead of spaces you have to use a separator. calling like this

```bash
buddy run app:build
buddy run app:start
...
```
